/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pawn.ricettacolo;
import it.unicam.cs.pawn.ricettacolo.Server.DefaultHttpServer;
import it.unicam.cs.pawn.ricettacolo.Server.DefaultServer;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        DefaultServer s = new DefaultHttpServer();
        try {
            s.createServer();


        } catch (Exception e) {
            e.printStackTrace();
        }


    }
}
